/*
 * This file was generated by the NOM IDL compiler for Voyager - DO NOT EDIT!
 *
 *
 * And remember, phase 3 is near...
 */
/*
 * Built from /Users/cinc/svn-sources/nom/trunk/nom/idl/nomarray.idl
 */
#ifndef NOM_NOMArray_IMPLEMENTATION_FILE
#define NOM_NOMArray_IMPLEMENTATION_FILE
#endif

#ifdef __OS2__
#define INCL_DOS
#include <os2.h>
#endif /* __OS2__ */

#include <nom.h>
#include <nomtk.h>

#include "nomarray.ih"

/**
 \brief This function implements the method length() of class NOMArray which returns the number of elements.
 */
NOMDLLEXPORT NOM_Scope gulong NOMLINK impl_NOMArray_length(NOMArray* nomSelf,
    CORBA_Environment *ev)
{
  NOMArrayData* nomThis = NOMArrayGetData(nomSelf);

  return _pPtrArray->len;
}

/**
 \brief This function implements the method append() of class NOMArray which adds an object to the end of the array.
 */
NOMDLLEXPORT NOM_Scope void NOMLINK impl_NOMArray_append(NOMArray* nomSelf,
    const NOMObject* pItem,
    CORBA_Environment *ev)
{
  NOMArrayData* nomThis = NOMArrayGetData(nomSelf);

  g_ptr_array_add(_pPtrArray, (gpointer) pItem);  
}


/**
 \brief This function implements the method queryObjectAtIdx() of class NOMArray.

 Idx is running from 0 to length()-1
 */
NOMDLLEXPORT NOM_Scope NOMObject* NOMLINK impl_NOMArray_queryObjectAtIdx(NOMArray* nomSelf,
                                                                         const gulong guIdx,
                                                                         CORBA_Environment *ev)
{
  NOMArrayData* nomThis = NOMArrayGetData(nomSelf);
  
  return (NOMObject*) g_ptr_array_index(_pPtrArray, guIdx);
}


/**
 \brief This function implements the overriden method nomInit() of class NOMArray which allocates our
 internal array data sructure.
 */
NOMDLLEXPORT NOM_Scope void NOMLINK impl_NOMArray_nomInit(NOMArray* nomSelf,
    CORBA_Environment *ev)
{
  NOMArrayData* nomThis = NOMArrayGetData(nomSelf);

  /* call parent */
  NOMArray_nomInit_parent(nomSelf, ev);
  
  /* */
  _pPtrArray=g_ptr_array_new();
  g_assert(_pPtrArray);
}

