/*
 * This file was generated by the NOM IDL compiler for Voyager - DO NOT EDIT!
 *
 *
 * And remember, phase 3 is near...
 */
/*
 * Built from /Users/cinc/svn-sources/nom/trunk/nom/idl/nomtestresult.idl
 */
#ifndef NOM_NOMTestResult_IMPLEMENTATION_FILE
#define NOM_NOMTestResult_IMPLEMENTATION_FILE
#endif

#if __OS2__
#define INCL_DOS
#include <os2.h>
#endif /* __OS2__ */

#include <nom.h>
#include <nomtk.h>

#include "nomtestresult.ih"

NOMDLLEXPORT NOM_Scope CORBA_boolean NOMLINK impl_NOMTestResult_success(NOMTestResult* nomSelf,
                                                                        CORBA_Environment *ev)
{
  /* NOMTestResultData* nomThis = NOMTestResultGetData(nomSelf); */
  CORBA_boolean nomRetval=FALSE;

  return nomRetval;
}

