# $Id: $
## @file
# Makefile for the NOM testcase.
#

DEPTH ?= ..
SUB_DEPTH = ..
include $(PATH_KBUILD)/subheader.kmk

ifdef NOM_WITH_TESTCASES

#
# The libnobjtk dll. (static lib isn't working for windows)
#
DLLS += libnomtest
libnomtest_TEMPLATE = nomdll
libnomtest_NAME.os2 = nomtest
libnomtest_DEFS = \
	NOM_AClass_IMPLEMENTATION_FILE \
	NOM_BClass_IMPLEMENTATION_FILE
libnomtest_INCS = idl
libnomtest_LDFLAGS.darwin = -install_name @executable_path/../lib/libnomtest.dylib
libnomtest_SOURCES = \
	idl/aclass.idl \
	idl/bclass.idl \
	class_c/aclass.c \
	class_c/bclass.c
libtest_SOURCES.os2 = \
	$(PATH_TARGET)/libnomtest-os2.def
libtest_SOURCES.win = \
	$(PATH_TARGET)/libnomtest-win.def


#
# Generates the OS/2 linker definition file.
#
$(PATH_TARGET)/libnomtest-os2.def: $(PATH_SUB_CURRENT)/exports.def | $(call DIRDEP,$(PATH_TARGET))
	$(RM) -f $@
	$(APPEND) $@ 'LIBRARY nobjtk INITINSTANCE TERMINSTANCE'
	$(APPEND) $@ 'PROTMODE'
	$(APPEND) $@ 'CODE PRELOAD DISCARDABLE'
	$(APPEND) $@ 'DATA MULTIPLE NONSHARED'
	$(APPEND) $@ "DESCRIPTION 'fixme using $(PRINTF)'"
	$(APPEND) $@ ""
	$(SED) \
		-e '/^PROTMODE/d' \
		-e '/^CODE/d' \
		-e '/^DATA/d' \
		-e '/^ *;/d' \
		--append $@ \
		$<

#
# Generates the Windows linker definition file.
#
$(PATH_TARGET)/libnomtest-win.def: $(PATH_SUB_CURRENT)/exports.def | $(call DIRDEP,$(PATH_TARGET))
	$(RM) -f $@
	$(APPEND) $@ 'LIBRARY libnomobjtk'
	$(SED) \
		-e '/^PROTMODE/d' \
		-e '/^CODE/d' \
		-e '/^DATA/d' \
		-e '/^[[:space:]]*;/d' \
		-e '/^[[:space:]]*$$/d' \
		-e 's/^[[:space:]][[:space:]]*/ /' \
		-e 's/^ _\([a-zA-Z0-9_]*Data\)/ \1 DATA/' \
		--append $@ \
		$<

#
# The test program.
#
PROGRAMS += test-nom
test-nom_TEMPLATE = nombin
test-nom_SOURCES = \
	c/test-nom.c
ifeq ($(BUILD_TARGET),win)
 test-nom_LIBS = \
	$(TARGET_libnomtest:.dll=.lib)
else
 test-nom_LIBS = \
	$(TARGET_libnomtest)
endif

#test-nom_LIBS= glib-2.0 \
#	$(TARGET_nobjtk_a) \
#	$(TARGET_nomtest_a)


test-nom_LIBS.linux = $(PATH_LIB)/libnomgc.so

endif # NOM_WITH_TESTCASES

include $(PATH_KBUILD)/subfooter.kmk


